### ISSUE TITLE
compare footprint and lcsc part footprint

### ISSUE THREAD

**Issue by Hoernchen** [Bouni/kicad-jlcpcb-tools#375] opened 2023-09-28 19:33 UTC
It would be quite useful to be able to check that the lcsc part number has the right footprint size for caps & resistors - the online viewer is great for spotting mistakes like accidentally selecting a 0603 parts for 0402 pads, but I'd prefer a button that would check this in kicad before uploading the board.

**Comment by venkatrao1** [comment] 2023-10-07 16:19
duplicate of #293, I think?

**Closed** 2023-10-26 05:31 UTC
Labels: duplicate
