### ISSUE TITLE
Installation not working using plugin manager

### ISSUE THREAD

**Issue by filimonic** [Bouni/kicad-jlcpcb-tools#270] opened 2023-01-24 19:12 UTC
**Describe the bug**
When adding repo URL to KiCad 6.0.10
22:08:03: Failure when receiving data from the peer
22:08:03: Unable to load repository url

**To Reproduce**
Add repo by url `https://raw.githubusercontent.com/Bouni/bouni-kicad-repository/main/repository.json` 
![image](https://user-images.githubusercontent.com/2893566/214385898-9a8ab2be-e8dd-4914-914b-a26d890cb5e9.png)

# KiCad Version
Application: KiCad (64-bit)

Version: (6.0.10), release build

Libraries:
	wxWidgets 3.2.1
	libcurl/7.86.0-DEV Schannel zlib/1.2.13

Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Dec 19 2022 21:23:04
	wxWidgets: 3.2.1 (wchar_t,wx containers)
	Boost: 1.80.0
	OCC: 7.6.2
	Curl: 7.86.0-DEV
	ngspice: 38
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

```
```

**Comment by Bouni** [comment] 2023-01-24 19:44
This is a known issue on Windows machines caused by the used libcurl. This happens for the download of official plugins as well. (The plugins itself, not the repo)

**Comment by DomoticX** [comment] 2023-01-28 17:23
This should be fixed in the KiCad 6.0.11 Release, reading the release notes:

**Windows**
[Use older version of curl that works correctly]

[https://www.kicad.org/blog/2023/01/KiCad-6.0.11-Release/](https://www.kicad.org/blog/2023/01/KiCad-6.0.11-Release/)

**Comment by Bouni** [comment] 2023-01-30 07:43
Fixed in Kicad `6.0.11` and `7.0.0-rc2-62-g971abcfc1a`

**Closed by Bouni** 2023-01-30 07:43 UTC
