### ISSUE TITLE
Wrong rotation and position of parts in JLCPCB in SMT assembly preview.

### ISSUE THREAD

**Issue by tibor-vavra** [Bouni/kicad-jlcpcb-tools#143] opened 2022-03-07 12:46 UTC
Hi,
thank you for this useful plugin.

I face an issue with right placing and rotation of parts in jlcpcb Review Parts Placement
![rotation_issue](https://user-images.githubusercontent.com/4319021/157036098-a52b04c4-ec93-4cad-bd1b-3700171c7945.png)

This is KiCad 3D Viewer
![3d_view](https://user-images.githubusercontent.com/4319021/157036023-056a6f0c-2977-4fb0-8857-d4c42e4e6d08.png)

The board design looks OK. Is there any way how can I correct it or I'm doing something wrong?
Thank you for your help.

My KiCad version is:

Application: KiCad PCB Editor (64-bit)

Version: (6.0.2), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Feb 12 2022 14:32:09
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.6.0
	Curl: 7.78.0-DEV
	ngspice: 36
	Compiler: Visual C++ 1928 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

**Comment by Bouni** [comment] 2022-03-09 06:30
Thats a known problem with THT components. 
The KiCAD footprints often have there center of rotation not in their actual center but JLC's parts do.
At the moment, you can upload it as it is and JLC's engeneers will fix the placements for you at no cost.
I've no good idea how to overcome that issue at the moment :confused:

**Comment by saschaludwig** [comment] 2022-03-21 21:58
I can give you access to my KiCad files on my gitlab for further investigation.

**Comment by Bouni** [comment] 2022-03-22 06:08
@saschaludwig That would be really helpful!

**Comment by Bouni** [comment] 2022-03-22 06:29
I just tried to create a little dummy project but relized that the fuse shown in the screenshot seems not to be part of the KiCAD standard library.
Did you create the footprint by yourself?

**Comment by Bouni** [comment] 2022-03-22 11:51
Just to explain whats going on under the hood:

If you use a 1x4 pin header (KiCAD footprint PinHeader_1x04_P2.54mm_Vertical) you get this in KiCAD:

![image](https://user-images.githubusercontent.com/948965/159475007-455f20c1-785c-4ef6-b4fa-bb04f00d6fd3.png)

If you open the footprint in the editor you see that the center of the footprint is exactly on Pin 1:

![image](https://user-images.githubusercontent.com/948965/159475122-757219d9-678a-4d70-b1f4-3a4705a34f92.png)

If you assign LCSC number C390680 for example, generate the fabrication files and upload them to JLC you will see this:

![image](https://user-images.githubusercontent.com/948965/159475231-25e11ab1-c02b-4651-b8bc-2d213c27e4c8.png)

So the rotation is off by 90° but also the center because JLC seems to set the center of rotation always to the center of the part and not the center of Pin 1!

I guess thats also the case for some SMD parts. @saschaludwig let me know which footprint you use and I'll take a look into it.

**Comment by saschaludwig** [comment] 2022-03-22 13:32
No, all parts are KiCad 6 standard parts.
And the rotation isn't the problem it looks like the created gerber + pos files created by the tools, trigger something that leads to a scaling somewhere along the JLCPCB processing. I will email you details about the project I have issues with.

**Comment by Bouni** [comment] 2022-03-22 13:50
I think I've seen that kind of issue before an it was something about imperial / metric settings 🤔 
Let me check, maybe I find the cause of this problem.

Also please post the version info of your KiCAD.

**Comment by saschaludwig** [comment] 2022-03-22 15:20
Okay, I found out that it has something to do with the origin of the files.
If I move the origin of the grid/placement to upper left corner of the board, I get distorted results like shown in the recent screenshots, even with manual export.
If I choose the placement origin to be in the lower left corner and have the coordinate system increasing on up/right I get matching results of footprints/layout.
So it has something to do with the origin of the files.

**Comment by bvernoux** [comment] 2022-03-23 18:40
I confirm JLCPCB preview is totally broken for connectors... I have asked them several time to fix it

**Comment by Bouni** [comment] 2022-04-05 09:43
I think there's no good solution for this at the moment. I will close this issue for now, you can re-open at any point in the future if you come up with a solution or if JLC offers one.

**Closed by Bouni** 2022-04-05 09:43 UTC
Labels: bug, maybe later
