### ISSUE TITLE
Add "Do not tint vias" option when generating fabrication files.

### ISSUE THREAD

**Issue by ethanhjennings** [Bouni/kicad-jlcpcb-tools#195] opened 2022-07-22 13:18 UTC
**Is your feature request related to a problem? Please describe.**
I like to use vias covered by solder mask to reduce the chance of shorts, but currently there's no way to enable this setting from this plugin.

**Describe the solution you'd like**
Maybe add a "settings" panel if there's other useful options or just a checkbox somewhere.

**Describe alternatives you've considered**
I have a workaround where I generate the gerber files through this plugin, then generate just the soldermask layers using the normal kicad flow, then rename and copy/paste in to replace them. But it would be nice if it was integrated into the plugin!

**Comment by Bouni** [comment] 2022-07-22 14:09
Vaild request. Also duplicate of #167

**Closed by Bouni** 2022-07-22 14:09 UTC
Labels: duplicate

**Comment by ethanhjennings** [comment] 2022-07-22 23:52
Apologies! I thought I checked but I missed #167.

Thanks for making this plugin!
