### ISSUE TITLE
Error message when click Plugin icon

### ISSUE THREAD

**Issue by ZoAndr** [Bouni/kicad-jlcpcb-tools#186] opened 2022-06-25 07:48 UTC
Problem

Good day!
Thanks a lot for amazing plugin!
I found some problem. Let me share with you.

**To Reproduce**
Error is appear when click icon of plugin in PCB design editor

**Describe the bug**
It is installed well. But when I try to call icon, it yields error message.
The error message contains text:
--------------------------------------------------------------
Traceback (most recent call last):

File
"...KiCad\6.0\3rdparty\plugins\com_github_bouni_kicad-jlcpcb-tools/plugin.py",
line 21, in Run
dialog = JLCPCBTools(None)

File
"...KiCad\6.0\3rdparty\plugins\com_github_bouni_kicad-jlcpcb-tools/mainwindow.py"
line 569, in init
self.init_store()

File
"...KiCad\6.0\3rdparty\plugins\com_github_bouni_kicad-jlcpcb-tools/mainwindow.py"
line 585, in init_store
self.populate_foootprint_list()

File
line 621, 
"...KiCad\6.0\3rdparty\plugins\com_github_bouni_kicad-jlcpcb-tools/mainwindow.py"
0: wx.dataview.DataViewIconText(

TypeError: DataVIewIconText(): arguments did not match any overloaded call:
overload 1: argument 2 has unexpected type 'Bitmap'
overload 2: argument 1 has unexpected type 'str'
---------------------------------------------------------------------

**Expected behavior**
Just no error

# KiCad Version
I am using KiCad 6.0.4 and tested in 6.0.6, results are same, Windows 10
Thanks a lot!!!

P.S. The idea and plugin are Great!!!

**Comment by ayourk** [comment] 2022-06-26 05:26
I believe this is a duplicate of https://github.com/Bouni/kicad-jlcpcb-tools/issues/181

**Comment by ZoAndr** [comment] 2022-06-26 07:37
Thank you!

**Closed** 2022-06-26 07:38 UTC
